### ISSUE TITLE
js files 404

### ISSUE THREAD

**Issue by fuyu** [rogierlommers/poddy#2]
These two files here return 404:
https://github.com/rogierlommers/poddy/blob/3337b495ea0da35d1d0d37f97741a3f0e14bf009/static/index.tmpl#L90-L91
Is this project maintained, can this be fixed?

**Comment by rogierlommers** [comment]
Hey @fuyu , I'll get back on this in a few days.

**Comment by rogierlommers** [comment]
Fixed; the files were obsolete...
